
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |-
{{ .Values.nginxConfig | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "nginx-html-files"
data:
{{- range $path, $bytes := .Files.Glob "files/*.html" }}
  {{ base $path }}: |-
{{ $bytes | toString | indent 4 }}
{{- end }}