{{ if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "fastapi.fullname" . }}-migrations"
  annotations:
    "helm.sh/hook": post-install, pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  {{- toYaml .Values.migrations.spec | nindent 2 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fastapi.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      securityContext:
            {{- toYaml .Values.migrations.securityContext | nindent 8 }}
      containers:
        - name: "{{ include "fastapi.fullname" . }}-migrations"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.migrations.command }}
          
          command: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migrations.args }}
          args: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.envAsMap }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $env := .Values.env }}
            - name: {{ $env.name }}
              {{- if $env.configMap }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $env.configMap }}
                  key: {{ $env.key }}
              {{- else if $env.secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $env.secret.name }}
                  key: {{ $env.secret.key }}
              {{- else }}
              value: {{ $env.value | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.migrations.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.migrations.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{ end }}