{{- if not (lookup "v1" "PersistentVolumeClaim" $.Release.Namespace .Values.persistentVolumeClaim.name) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    type: {{ .Values.persistentVolume.labels.type }}
  annotations:
    "helm.sh/hook": post-install, pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  accessModes:
     {{- toYaml .Values.persistentVolumeClaim.accessModes | nindent 12 }}
  resources:
    requests:
       storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}
{{- end }}