apiVersion: v1
kind: Pod
metadata:
  name: keycloak-backup
spec:
  containers:
  - name: keycloak-backup
    image: "bitnami/keycloak:26.0.7-debian-12-r0"
    env:
      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
        value: Keycloak123
      - name: KEYCLOAK_DATABASE_NAME
        value: keycloak
      - name: KEYCLOAK_DATABASE_HOST
        value: postgres
      - name: KEYCLOAK_DATABASE_PORT
        value: "5432"
      - name: KEYCLOAK_DATABASE_USER
        value: postgres
      - name: KEYCLOAK_DATABASE_PASSWORD
        value: Postgres123
      - value: KEYCLOAK_CACHE_TYPE
        name: local